services:
  - type: web
    name: spring-backend
    runtime: java
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
